version: '3'

services:
  my-tools-mariadb:
    image: "mariadb"
    container_name: my-tools-mariadb
    volumes:
      - my-tools-db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-tools-db
      MYSQL_USER: my_tools_user
      MYSQL_PASSWORD: my_tools_user

  my-tools-app:
    build: ./backend
    container_name: my-tools-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://localhost:3306/my-tools-db
      - SPRING_DATASOURCE_USERNAME=my_tools_user
      - SPRING_DATASOURCE_PASSWORD=my_tools_user
      - FILE_SERVICE_STORAGE_FOLDER=/file-service/storage/
    ports:
      - 8081:8081
    links:
      - my-tools-mariadb

volumes:
  my-tools-db-data:
