services:
  my-tools-mariadb:
    image: mariadb:latest
    container_name: my-tools-mariadb
    volumes:
      - my-tools-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-tools-db
      MYSQL_USER: my_tools_user
      MYSQL_PASSWORD: my_tools_user
    ports:
      - 3500:3500

  my-tools-app:
    build: ./backend
    container_name: my-tools-app
    volumes:
      - ${FILE_SERVICE_STORAGE_FOLDER_HOST}:/app/file-service/storage
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://my-tools-mariadb/my-tools-db
      - SPRING_DATASOURCE_USERNAME=my_tools_user
      - SPRING_DATASOURCE_PASSWORD=my_tools_user
      - SPRING_DATASOURCE_DATABASE_NAME=my-tools-db
      - FILE_SERVICE_STORAGE_FOLDER=/app/file-service/storage
      - TRANSLATION_GOOGLE_API_KEY=${TRANSLATION_GOOGLE_API_KEY}
      - EPUB_APP_FILES_RELATIVE_PATH=${EPUB_APP_FILES_RELATIVE_PATH}
      - GLOBAL_TMP_FILES_RELATIVE_PATH=${GLOBAL_TMP_FILES_RELATIVE_PATH}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - BACKUP_PATH_STORAGE_FOLDER=${BACKUP_PATH_STORAGE_FOLDER}
    ports:
      - 8091:8081
    depends_on:
      - my-tools-mariadb

volumes:
  my-tools-db-data:
  my-tools-storage-data:
